### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Poussinou**
Hi,

This small PR adds a button to get your app on F-Droid 👍 

You might tell @izzysoft if you want to keep your app in his repo now that your app reached the official F-Droid repo? If you don't keep it in his repo, then you can remove IzzyOnDroid's badge.

You can now eventually add the [fdroid](https://github.com/topics/fdroid) and/or [f-droid](https://github.com/topics/f-droid) tags that will appear on the right side of the repo.

### CODE REVIEW

**Review by w2sv — APPROVED** [review]

**Comment by w2sv** [comment]
Thank you!

**Comment by IzzySoft** [comment]
@w2sv shall I mark it to be kept in my repo then? I see the Readme now has both badges. Putting up a note on my end helps deciding faster then :wink:

**Comment by w2sv** [comment]
@IzzySoft I guess we can take it out of your repo, I'll update the README forthwith. Thank you for having hosted me up until now!

**Comment by IzzySoft** [comment]
OK, noted – thanks! Will remove it then after a decent overlap (usually around 2 weeks).

**Comment by IzzySoft** [comment]
I took the freedom to return WiFi-Widget to IoD today (effective with the next sync) – with the added plus to confirm it as [Reproducible Build](https://reproducible-builds.org/) (see e.g. [Reproducible Builds, special client support and more at IzzyOnDroid](https://android.izzysoft.de/articles/named/iod-rbs-mirrors-clients) for some background on this). As at IzzyOnDroid, we no longer have the policy to remove apps just because they became available at F-Droid.org, I'm currently walking those we had "removed" (metadata were kept) to see which are still actively maintained and should be returned… So feel welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to return it to your Readme in turn of the return :stuck_out_tongue_winking_eye:

**Pull request merged**
